// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VizvezetekWebAPI.Data;

#nullable disable

namespace VizvezetekWebAPI.Migrations
{
    [DbContext(typeof(SzereloDbContext))]
    [Migration("20251104080815_sqlite.local_migration_708")]
    partial class sqlitelocal_migration_708
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("VizvezetekWebAPI.Models.Hely", b =>
                {
                    b.Property<int>("Az")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Utca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Az");

                    b.ToTable("Helyek");
                });

            modelBuilder.Entity("VizvezetekWebAPI.Models.Munkalap", b =>
                {
                    b.Property<int>("Az")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnyagAr")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BeDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("HelyAz")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("JavDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("MunkaOra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SzereloAz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Az");

                    b.HasIndex("HelyAz");

                    b.HasIndex("SzereloAz");

                    b.ToTable("Munkalapok");
                });

            modelBuilder.Entity("VizvezetekWebAPI.Models.Szerelo", b =>
                {
                    b.Property<int>("Az")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KezdEv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Az");

                    b.ToTable("Szerelok");
                });

            modelBuilder.Entity("VizvezetekWebAPI.Models.Munkalap", b =>
                {
                    b.HasOne("VizvezetekWebAPI.Models.Hely", "Hely")
                        .WithMany("Munkalapok")
                        .HasForeignKey("HelyAz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VizvezetekWebAPI.Models.Szerelo", "Szerelo")
                        .WithMany("Munkalapok")
                        .HasForeignKey("SzereloAz")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hely");

                    b.Navigation("Szerelo");
                });

            modelBuilder.Entity("VizvezetekWebAPI.Models.Hely", b =>
                {
                    b.Navigation("Munkalapok");
                });

            modelBuilder.Entity("VizvezetekWebAPI.Models.Szerelo", b =>
                {
                    b.Navigation("Munkalapok");
                });
#pragma warning restore 612, 618
        }
    }
}
